import Head from "next/head";
import { useRouter } from "next/router";
import { useContext, useEffect, useState } from "react";
import { UserDataContext } from "@/context/UserContext";
import { signOutUser } from "@/auth/firebase-auth";

export default function PublicRelationHomePage() {
  const userData = useContext(UserDataContext);
  const [navBar, setNavbar] = useState(false);
  const router = useRouter();

  useEffect(() => {
    if (userData) {
      switch (userData.role) {
        case "student":
          router.push("/student/");
          break;
        case "public_relation":
          router.push("/public-relation/");
          break;
        case "company":
          router.push("/company/");
          break;
        default:
          router.push("/");
      }
    }
  }, [userData, router]);
  return (
    <>
      <Head>
        <title>Public Relation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      halo bang
      <button onClick={signOutUser}>Sign Out</button>
    </>
  );
}
