import Head from "next/head";
import NavbarPR from "@/components/public-relation/Navbar";
import { useRouter } from "next/router";
import { useContext, useEffect, useState } from "react";
import { UserContext, UserDataContext } from "@/context/UserContext";
import { signOutUser } from "@/auth/firebase-auth";
import { collection, getCountFromServer, getDocs } from "firebase/firestore";
import { db } from "@/lib/firebase";

export default function PublicRelationHomePage() {
  const [navbar, setNavbar] = useState(false);
  const user = useContext(UserContext);
  const userData = useContext(UserDataContext);
  const router = useRouter();

  useEffect(() => {
    if (!user || !userData) {
      router.push("/auth/login");
    }
    setTimeout(() => {
      if (userData.role !== "public_relation") {
        router.push("/auth/login");
      }
    }, 1000);
  }, [userData, router, user]);

  if (!user || !userData) {
    return null;
  }

  // getCountFromServer(collection(db,"users")).then(snap=> console.log(snap.data().count))

  return (
    <>
      <Head>
        <title>Public Relation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarPR navBar={navbar} setNavbar={setNavbar}></NavbarPR>
      <button onClick={signOutUser}>Sign Out</button>
    </>
  );
}
