import Head from "next/head";
import NavbarPR from "@/components/public-relation/Navbar";
import SideBarPR from "@/components/public-relation/Sidebar";
import ConfirmationModal from "@/components/ConfirmationModal";
import StudentDetail from "@/components/public-relation/StudentDetail";
import { db } from "@/lib/firebase";
import { doc, getDoc } from "firebase/firestore";
import { getDocumentsId } from "@/lib/firestore";
import { useContext, useEffect, useState } from "react";
import { UserContext, UserDataContext } from "@/context/UserContext";
import { useRouter } from "next/router";
import { signOutUser } from "@/auth/firebase-auth";

export async function getStaticPaths() {
  const paths = await getDocumentsId("students");
  return {
    paths,
    fallback: false,
  };
}

export async function getServerSideProps({ params }) {
  const studentDetail = await getDoc(doc(db, "students", params.id));
  const studentDetailData = {
    id: studentDetail.id,
    ...studentDetail.data(),
  };
  return {
    props: {
      studentDetailData,
    },
  };
}

export default function StudentDetailPage({ studentDetailData }) {
  const user = useContext(UserContext);
  const userData = useContext(UserDataContext);
  const router = useRouter();
  const [sidebar, setSidebar] = useState(false);
  const [ShowLogOutConfirmation, setShowLogOutConfirmation] = useState(false);

  useEffect(() => {
    if (!user) {
      router.push("/auth/login");
    }
    if (user == null || userData.role !== "public_relation") {
      router.push("/auth/login");
    }
  }, [userData, router, user]);

  return (
    <>
      <Head>
        <title>Student</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/internwolu.ico" />
      </Head>
      <NavbarPR sidebar={sidebar} setSidebar={setSidebar}></NavbarPR>
      <SideBarPR
        sidebar={sidebar}
        setShowLogOutConfirmation={setShowLogOutConfirmation}
      ></SideBarPR>
      <div class={`lg:ml-64`}>
        <div class="rounded-lg mt-14">
          <StudentDetail studentDetailData={studentDetailData}></StudentDetail>
          {ShowLogOutConfirmation && (
            <ConfirmationModal
              actionFunction={signOutUser}
              setShowConfirmationModal={setShowLogOutConfirmation}
              message={"Apakah anda yakin ingin keluar?"}
            ></ConfirmationModal>
          )}
        </div>
      </div>
    </>
  );
}
