import Head from "next/head";
import StudentDataInputForm from "@/components/student/StudentDataInput";
import JoinPersonLogo from "../../../public/logo/join.svg";
import NextButtonIcon from "../../../public/icon/next-button-icon.svg";
import { useState } from "react";

export default function SignInPage() {
  const [nextPage, setNextPage] = useState(false);
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {nextPage ? (
        <div>
          <StudentDataInputForm></StudentDataInputForm>
        </div>
      ) : (
        <div className="mx-auto flex items-center my-24 flex-col md:w-[400px]">
          <div className="md:w-[400px]">
            <h2 className="font-[600] text-2xl leading-7 w-[240px] text-left md:w-[90%] mx-auto">
              Before proceeding, please complete your personal data
            </h2>
            <div className="mt-12 flex justify-center">
              <JoinPersonLogo />
            </div>
          </div>
          <button onClick={() => setNextPage(!nextPage)} className="bg-primary-color mt-20 py-3 rounded-md px-[14px] text-center items-end ml-auto"><NextButtonIcon/></button>
        </div>
      )}
    </>
  );
}
