import Head from "next/head";
import StudentDataInputForm from "@/components/student/StudentDataInput";
import JoinPersonLogo from "../../../public/logo/join.svg";
import NextButtonIcon from "../../../public/icon/next-button-icon.svg";
import { auth } from "@/lib/firebase";
import { useContext, useEffect, useState } from "react";
import { useRouter } from "next/router";
import { redirectCurrentUserToLoginPage } from "@/utils/redirectUser";
import { UserContext, UserDataContext } from "@/context/UserContext";

export default function StudentDataInput() {
  const [nextPage, setNextPage] = useState(false);
  const user = useContext(UserContext);
  const userData = useContext(UserDataContext);
  const router = useRouter();

  useEffect(() => {
    if (!user) {
      router.push("/auth/login");
    }
    if (user == null || userData.role !== "student") {
      router.push("/auth/login");
    }
  }, [userData, router, user]);

  return (
    user && (
      <>
        <Head>
          <title>Register</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {nextPage ? (
          <div>
            <StudentDataInputForm></StudentDataInputForm>
          </div>
        ) : (
          <div className="mx-auto py-24 bg-white h-full sm:max-w-md sm:shadow-md">
            <div className="flex flex-col w-full">
              <h2 className="font-[600] text-3xl leading-7 w-[300px] text-left md:w-[90%] mx-auto font-sans">
                Before proceeding, please complete your personal data
              </h2>
              <div className="mt-12 flex justify-center">
                <JoinPersonLogo />
              </div>
            </div>
            <button
              onClick={() => setNextPage(!nextPage)}
              className="bg-primary-color mt-20 rounded-md text-center  py-4 px-5 float-right mr-10"
            >
              <NextButtonIcon />
            </button>
          </div>
        )}
      </>
    )
  );
}
