import Head from "next/head";
import SignUpForm from "@/components/SignUp";

export default function SignUpPage() {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/internwolu.ico" />
      </Head>
      <SignUpForm></SignUpForm>
    </>
  );
}
