import Head from "next/head";
import { onAuthStateChanged } from "firebase/auth";
import { useRouter } from "next/router";
import { auth } from "@/lib/firebase";
import { gettingUserRole } from "@/utils/redirectUser";

export default function Home() {
  const router = useRouter();
  // const user = auth.currentUser;
  // console.log(user);

  // if (typeof window !== "undefined") {
  //   if (!user) {
  //     router.push("auth/login");
  //   } else {
  //     router.push("/student/");
  //   }
  // }

  onAuthStateChanged(auth, async (user) => {
    if (!user) {
      router.push("auth/login");
    }
    router.push("/student/");
  });
  
  return (
    <>
      <Head>
        <title>PKL PROJECT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
