import Head from "next/head";
import { useAuth } from "@/utils/redirectUser";
import { useRouter } from "next/router";

export default function Home() {
  const user = useAuth();
  const router = useRouter();

  if (typeof window !== "undefined") {
    !user && router.push("/auth/login");
  }

  return (
    <>
      <Head>
        <title>PKL PROJECT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
