import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { useState } from "react";



// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [navBar, setNavbar] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar navBar={navBar} setNavbar={setNavbar}></Navbar>
      <main onClick={() => setNavbar(!navBar)}>
        <div className='mt-96 text-center font-bold'> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quae eum veniam sit possimus, cum quasi magnam vitae facilis magni dolorem perferendis totam distinctio doloribus doloremque consectetur deleniti, veritatis tempora soluta aut, pariatur maxime nisi error? Nisi, vitae. Quasi neque inventore dolores accusamus quis voluptatibus totam laborum nemo nostrum! Pariatur, mollitia?</div>
        <div className='mt-96 text-center font-bold'> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quae eum veniam sit possimus, cum quasi magnam vitae facilis magni dolorem perferendis totam distinctio doloribus doloremque consectetur deleniti, veritatis tempora soluta aut, pariatur maxime nisi error? Nisi, vitae. Quasi neque inventore dolores accusamus quis voluptatibus totam laborum nemo nostrum! Pariatur, mollitia?</div>
        <div className='mt-96 text-center font-bold'> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quae eum veniam sit possimus, cum quasi magnam vitae facilis magni dolorem perferendis totam distinctio doloribus doloremque consectetur deleniti, veritatis tempora soluta aut, pariatur maxime nisi error? Nisi, vitae. Quasi neque inventore dolores accusamus quis voluptatibus totam laborum nemo nostrum! Pariatur, mollitia?</div>
      </main>
    </>
  )
}
