import Head from "next/head";
import About from "@/components/About";
import { useRouter } from "next/router";
import { useContext, useEffect} from "react";
import { UserContext, UserDataContext } from "@/context/UserContext";

export default function AboutPage() {
  const user = useContext(UserContext);
  const userData = useContext(UserDataContext);
  const router = useRouter();

  useEffect(() => {
    if (!user) {
      router.push("/auth/login");
    }
    if (user == null || userData.role !== "student") {
      router.push("/auth/login");
    }
  }, [userData, router, user]);
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/internwolu.ico" />
      </Head>
      <About></About>
    </>
  )
}
