import Head from "next/head";
import Navbar from "@/components/student/Navbar";
import CompanyList from "@/components/CompanyList";
import { useRouter } from "next/router";
import { useContext, useEffect, useState } from "react";
import { UserContext, UserDataContext } from "@/context/UserContext";

export default function StudentHomePage() {
  const user = useContext(UserContext);
  const userData = useContext(UserDataContext);
  const [navbar, setNavbar] = useState(false);
  const router = useRouter();

  useEffect(() => {
    if (!user || !userData) {
      router.push("/auth/login");
    } else if (userData.role !== "student") {
      router.push("/auth/login");
    }
  }, [userData, router, user]);

  if (!user || !userData) {
      return null;
  }
  return (
    <>
      <Head>
        <title>Student</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar navBar={navbar} setNavbar={setNavbar}></Navbar>
      <CompanyList onClick={() => setNavbar(false)}></CompanyList>
    </>
  );
}
