import Head from "next/head";
import Navbar from "@/components/student/Navbar";
import { db } from "@/lib/firebase";
import { auth } from "@/lib/firebase";
import { useRouter } from "next/router";
import { useContext, useEffect, useState } from "react";
import { redirectCurrentUserToLoginPage } from "@/utils/redirectUser";
import { signOutUser } from "@/auth/firebase-auth";
import CompanyPage from "@/components/student/CompanyPage";
import { UserContext } from "@/context/UserContext";
import { doc, getDoc } from "firebase/firestore";

export default function Student() {
  const user = useContext(UserContext);
  const [navBar, setNavbar] = useState(false);
  const router = useRouter();
  if (!user) {
    router.push("/auth/login");
    return null;
  } 

  return (
    user && (
      <>
        <Head>
          <title>Student</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar navBar={navBar} setNavbar={setNavbar}></Navbar>
        <CompanyPage onClick={() => setNavbar(false)}></CompanyPage>
      </>
    )
  );
}
